/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Link */
        post: operations["verify_link_auth_verify_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Code */
        post: operations["resend_code_auth_resend_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_me_patch"];
        trace?: never;
    };
    "/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Stats
         * @description Расширенная статистика точности по темам (Pro-функция, иначе 402).
         *
         *     Решение по не-Pro: пейволл 402 pro_required — урезанную версию не отдаём,
         *     т.к. это явная Pro-ценность (release2.md §A).
         */
        get: operations["my_stats_me_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/avatar/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign Avatar */
        post: operations["presign_avatar_me_avatar_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/avatar/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Avatar */
        post: operations["confirm_avatar_me_avatar_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Profile
         * @description Публичный профиль (SEO). Забаненный/несуществующий → 404.
         */
        get: operations["public_profile_users__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training */
        get: operations["training_tasks_training_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submit_answer_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Position */
        get: operations["get_my_position_leaderboard_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily */
        get: operations["get_daily_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Daily */
        post: operations["answer_daily_daily_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Leaderboard */
        get: operations["daily_leaderboard_daily_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Me */
        get: operations["daily_me_daily_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/review/{duel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_ai_review__duel_id__get"];
        put?: never;
        /** Request Review */
        post: operations["request_review_ai_review__duel_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_admin_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_admin_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_admin_tasks__task_id__patch"];
        trace?: never;
    };
    "/admin/tasks/{task_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Task */
        post: operations["publish_task_admin_tasks__task_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tasks/{task_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Task */
        post: operations["reject_task_admin_tasks__task_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ban User */
        post: operations["ban_user_admin_users__user_id__ban_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/unban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unban User */
        post: operations["unban_user_admin_users__user_id__unban_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/grant-pro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Pro
         * @description Выдать/продлить Pro на N дней (только admin). Идемпотентно-безопасно.
         */
        post: operations["grant_pro_admin_users__user_id__grant_pro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/revoke-pro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Pro
         * @description Отозвать Pro (только admin). Идемпотентно.
         */
        post: operations["revoke_pro_admin_users__user_id__revoke_pro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metrics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Overview */
        get: operations["metrics_overview_admin_metrics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flags */
        get: operations["list_flags_admin_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/feature-flags/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Flag */
        put: operations["upsert_flag_admin_feature_flags__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Проверяет доступность PostgreSQL и Redis.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminTask
         * @description Задача в админке — с эталоном (закрытый роутер).
         */
        AdminTask: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** Difficulty */
            difficulty: number;
            type: components["schemas"]["TaskType"];
            /** Body */
            body: {
                [key: string]: unknown;
            };
            /** Answer */
            answer: {
                [key: string]: unknown;
            };
            /** Explanation */
            explanation: string | null;
            status: components["schemas"]["TaskStatus"];
            /** Author Id */
            author_id: string | null;
            /** Version */
            version: number;
        };
        /**
         * AdminTaskList
         * @description Страница задач.
         */
        AdminTaskList: {
            /** Items */
            items: components["schemas"]["AdminTask"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * AdminUser
         * @description Пользователь в админке.
         */
        AdminUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Banned At */
            banned_at: string | null;
        };
        /** AdminUserList */
        AdminUserList: {
            /** Items */
            items: components["schemas"]["AdminUser"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * AiReviewResponse
         * @description Публичный статус разбора (POST/GET /ai/review/{duel_id}).
         */
        AiReviewResponse: {
            status: components["schemas"]["AiReviewStatus"];
            /** Content */
            content?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * AiReviewStatus
         * @enum {string}
         */
        AiReviewStatus: "pending" | "done" | "failed";
        /**
         * AnswerPayload
         * @description Полезная нагрузка ответа на quiz: индекс выбранной опции.
         */
        AnswerPayload: {
            /** Selected */
            selected: number;
        };
        /**
         * AnswerResult
         * @description Результат проверки ответа (соло-режим).
         */
        AnswerResult: {
            /** Correct */
            correct: boolean;
            /** Correct Option */
            correct_option: number;
            /** Explanation */
            explanation: string;
            /** Already Solved */
            already_solved: boolean;
        };
        /**
         * AnswerSubmit
         * @description POST /answers — ответ в соло-режиме.
         */
        AnswerSubmit: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            answer: components["schemas"]["AnswerPayload"];
            /** Time Ms */
            time_ms: number;
        };
        /**
         * AvatarConfirmRequest
         * @description POST /me/avatar/confirm — подтверждение загруженного объекта.
         */
        AvatarConfirmRequest: {
            /** Key */
            key: string;
        };
        /**
         * AvatarPresignRequest
         * @description POST /me/avatar/presign — параметры будущей загрузки.
         */
        AvatarPresignRequest: {
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp";
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * AvatarPresignResponse
         * @description Ответ presign: куда и как грузить аватар напрямую в MinIO.
         */
        AvatarPresignResponse: {
            /** Upload Url */
            upload_url: string;
            /** Key */
            key: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * BanRequest
         * @description POST /admin/users/{id}/ban — причина бана (журналируется).
         */
        BanRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * DailyAnswerResult
         * @description Результат проверки дневного ответа.
         *
         *     ``scored`` — учтён ли ответ в лидерборде (только первый зачётный за день).
         *     ``already_answered`` — был ли зачётный ответ ранее сегодня.
         */
        DailyAnswerResult: {
            /** Correct */
            correct: boolean;
            /** Correct Option */
            correct_option: number;
            /** Explanation */
            explanation: string;
            /** Scored */
            scored: boolean;
            /** Already Answered */
            already_answered: boolean;
        };
        /**
         * DailyAnswerSubmit
         * @description POST /daily/answer — ответ на задачу дня.
         */
        DailyAnswerSubmit: {
            answer: components["schemas"]["AnswerPayload"];
            /** Time Ms */
            time_ms: number;
        };
        /**
         * DailyLeaderboardEntry
         * @description Строка дневного лидерборда (обогащена ником/аватаром).
         */
        DailyLeaderboardEntry: {
            /** Rank */
            rank: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Score */
            score: number;
        };
        /**
         * DailyMyPosition
         * @description GET /daily/me — моя позиция в дневном лидерборде.
         */
        DailyMyPosition: {
            /** Rank */
            rank: number | null;
            /** Score */
            score: number | null;
        };
        /**
         * DailyTask
         * @description GET /daily — задача дня (без эталона).
         */
        DailyTask: {
            /**
             * Challenge Date
             * Format: date
             */
            challenge_date: string;
            task: components["schemas"]["TaskPublic"];
        };
        /** FeatureFlagOut */
        FeatureFlagOut: {
            /** Key */
            key: string;
            /** Enabled */
            enabled: boolean;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FeatureFlagUpsert
         * @description PUT /admin/feature-flags/{key}.
         */
        FeatureFlagUpsert: {
            /** Enabled */
            enabled: boolean;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * GrantProRequest
         * @description POST /admin/users/{id}/grant-pro — продлить Pro на N дней.
         */
        GrantProRequest: {
            /** Days */
            days: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LeaderboardEntry
         * @description Одна строка лидерборда.
         */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Elo */
            elo: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MetricsOverview */
        MetricsOverview: {
            /** Users */
            users: number;
            /** Duels 24H */
            duels_24h: number;
            /** Duels 7D */
            duels_7d: number;
            /** Published Tasks */
            published_tasks: number;
            /** Active Subscriptions */
            active_subscriptions: number;
        };
        /**
         * MyLeaderboardPosition
         * @description GET /leaderboard/me — моя позиция и соседи ±2 (rank=null если меня нет).
         */
        MyLeaderboardPosition: {
            /** Rank */
            rank: number | null;
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /**
         * ProStatus
         * @description Результат grant/revoke: текущее состояние подписки пользователя.
         */
        ProStatus: {
            /** Is Pro */
            is_pro: boolean;
            /** Current Period End */
            current_period_end: string | null;
        };
        /**
         * QuizBody
         * @description body для type=quiz (включая код-вопросы: сниппет в code).
         */
        QuizBody: {
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Code */
            code?: string | null;
            /** Language */
            language?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * RegisterResponse
         * @description Единый ответ register для обоих режимов.
         *
         *     OFF: verification_required=false + токены (авто-логин).
         *     ON: verification_required=true (код отправлен, токенов нет).
         */
        RegisterResponse: {
            /** Verification Required */
            verification_required: boolean;
            /** Access Token */
            access_token?: string | null;
            /** Token Type */
            token_type?: string | null;
            /** Expires In */
            expires_in?: number | null;
        };
        /** ResendCodeRequest */
        ResendCodeRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * TaskCreate
         * @description POST /admin/tasks — создание (всегда стартует в draft).
         */
        TaskCreate: {
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** Difficulty */
            difficulty: number;
            type: components["schemas"]["TaskType"];
            /** Body */
            body: {
                [key: string]: unknown;
            };
            /** Answer */
            answer: {
                [key: string]: unknown;
            };
            /** Explanation */
            explanation?: string | null;
        };
        /**
         * TaskPublic
         * @description Публичная задача для тренировки — без answer и explanation.
         */
        TaskPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["TaskType"];
            /** Difficulty */
            difficulty: number;
            body: components["schemas"]["QuizBody"];
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "draft" | "review" | "published";
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "quiz" | "code_bug" | "sql" | "design";
        /**
         * TaskUpdate
         * @description PATCH /admin/tasks/{id} — частичное обновление редактируемых полей.
         */
        TaskUpdate: {
            /** Difficulty */
            difficulty?: number | null;
            /** Body */
            body?: {
                [key: string]: unknown;
            } | null;
            /** Answer */
            answer?: {
                [key: string]: unknown;
            } | null;
            /** Explanation */
            explanation?: string | null;
        };
        /**
         * TokenResponse
         * @description Access-токен отдаётся в JSON; refresh — в httpOnly cookie.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * TopicAccuracy
         * @description Точность пользователя по одной теме за период (расширенная статистика).
         */
        TopicAccuracy: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Accuracy */
            accuracy: number;
            /** Avg Time Ms */
            avg_time_ms: number;
        };
        /** TopicPublic */
        TopicPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /**
         * TopicRating
         * @description Эло пользователя по одной теме (для публичного профиля).
         */
        TopicRating: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Elo */
            elo: number;
        };
        /**
         * UserMe
         * @description Профиль для самого пользователя — добавляем email и Pro-статус.
         */
        UserMe: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Avatar Key */
            avatar_key: string | null;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Is Pro
             * @default false
             */
            is_pro: boolean;
            /**
             * Avatar Url
             * @description Публичный URL аватара: S3_PUBLIC_BASE_URL/avatars/{key}.
             */
            readonly avatar_url: string | null;
        };
        /**
         * UserProfile
         * @description Публичный профиль GET /users/{username} — без чувствительных полей.
         */
        UserProfile: {
            /** Username */
            username: string;
            /** Avatar Url */
            avatar_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Pro */
            is_pro: boolean;
            /** Topics */
            topics: components["schemas"]["TopicRating"][];
            /** Total Duels */
            total_duels: number;
            /** Wins */
            wins: number;
            /** Win Rate */
            win_rate: number;
            /** Streak */
            streak: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "moderator" | "admin";
        /**
         * UserStats
         * @description Расширенная статистика профиля (GET /me/stats) — Pro-функция.
         *
         *     Полная версия (Pro): агрегаты точности по темам за period + total.
         *     Решение по не-Pro: пейволл 402 pro_required (см. router), урезанной версии
         *     не отдаём — это явная Pro-ценность (см. release2.md §A).
         */
        UserStats: {
            /** Period Days */
            period_days: number;
            /** Total Answered */
            total_answered: number;
            /** Total Correct */
            total_correct: number;
            /** Overall Accuracy */
            overall_accuracy: number;
            /** Topics */
            topics: components["schemas"]["TopicAccuracy"][];
        };
        /**
         * UserUpdate
         * @description PATCH /me — изменяемые поля.
         */
        UserUpdate: {
            /** Username */
            username?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Code */
            code: string;
        };
        /** VerifyLinkRequest */
        VerifyLinkRequest: {
            /** Token */
            token: string;
        };
        /**
         * VerifyLinkResponse
         * @description verify-link: на том же устройстве — авто-логин; на другом — только подтверждение.
         *
         *     Код в БД лежит только хэшем, в открытом виде его взять неоткуда. На другом
         *     устройстве пользователь берёт код из своего же письма и вводит на устройстве
         *     регистрации — поэтому здесь код не возвращается.
         */
        VerifyLinkResponse: {
            /** Logged In */
            logged_in: boolean;
            /** Access Token */
            access_token?: string | null;
            /** Token Type */
            token_type?: string | null;
            /** Expires In */
            expires_in?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_link_auth_verify_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_code_auth_resend_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    update_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_stats_me_stats_get: {
        parameters: {
            query?: {
                /** @description Период в днях */
                period?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_avatar_me_avatar_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvatarPresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarPresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_avatar_me_avatar_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvatarConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_profile_users__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicPublic"][];
                };
            };
        };
    };
    training_tasks_training_get: {
        parameters: {
            query: {
                topic: string;
                difficulty?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_leaderboard_get: {
        parameters: {
            query?: {
                scope?: "global" | "weekly";
                topic?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_position_leaderboard_me_get: {
        parameters: {
            query?: {
                scope?: "global" | "weekly";
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyLeaderboardPosition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_daily_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyTask"];
                };
            };
        };
    };
    answer_daily_daily_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyAnswerSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyAnswerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_leaderboard_daily_leaderboard_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLeaderboardEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_me_daily_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyMyPosition"];
                };
            };
        };
    };
    get_review_ai_review__duel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                duel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_review_ai_review__duel_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                duel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_admin_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                topic?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTaskList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_admin_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_admin_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_task_admin_tasks__task_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_task_admin_tasks__task_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTask"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ban_user_admin_users__user_id__ban_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unban_user_admin_users__user_id__unban_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_pro_admin_users__user_id__grant_pro_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantProRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_pro_admin_users__user_id__revoke_pro_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_overview_admin_metrics_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOverview"];
                };
            };
        };
    };
    list_flags_admin_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagOut"][];
                };
            };
        };
    };
    upsert_flag_admin_feature_flags__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureFlagUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
